name: Prettier

on:
    - pull_request

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ^16.0.0
            - run: npm install
            - run: npx prettier --check .
